spring:
  profile.active: production
  application.name:
    api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PSW}

  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate:
      format_sql: false

server.error.include-stacktrace: never
